// <auto-generated />
namespace NVC_Food_APP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class p3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(p3));
        
        string IMigrationMetadata.Id
        {
            get { return "201805290635187_p3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
